# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 416395108155b621a706b5688a1f623014c2ffaac723b0ce8efd9b9c735d28fe7225228584b869c522c25145859112013ce325ccd8313d05cb62bb7a5035960d

test:
  secret_key_base: ae5f7a7b2f7eeecae55f437801854c5b1d4d1473190460eb9b0ed53d9c4b4997394b6e9239f9fd1c47e12d5f4d223760926ed7060d026b0cb4c6d28f2e3a27f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
